interface Colors {
  warning: string
  success: string
  successReduced: string
  successContrast: string
  textStrongest: string
  textStronger: string
  textStrong: string
  text: string
  textWeak: string
  textWeaker: string
  textWeakest: string
  textContrast: string
  background: string
  background50: string
  background100: string
  background200: string
  background300: string
  background400: string
  background500: string
  background600: string
  background700: string
  background800: string
  background900: string
  theme: string
  themeHover: string
  themeLight: string
  themeContrast: string
  highlight: string
  highlightHover: string
  highlightContrast: string
  highlightLight: string
  cta: string
  ctaHover: string
  ctaContrast: string
  error: string
}
