export default {
  txt: {
    strongest: 'var(--color-text-strongest)',
    stronger: 'var(--color-text-stronger)',
    strong: 'var(--color-text-strong)',
    DEFAULT: 'var(--color-text)',
    weak: 'var(--color-text-weak)',
    weaker: 'var(--color-text-weaker)',
    weakest: 'var(--color-text-weakest)',
    contrast: 'var(--color-text-contrast)',
  },
  bgr: {
    DEFAULT: 'var(--color-background)',
    50: 'var(--color-background-50)',
    100: 'var(--color-background-100)',
    200: 'var(--color-background-200)',
    300: 'var(--color-background-300)',
    400: 'var(--color-background-400)',
    500: 'var(--color-background-500)',
    600: 'var(--color-background-600)',
    700: 'var(--color-background-700)',
    800: 'var(--color-background-800)',
    900: 'var(--color-background-900)',
  },
  thm: {
    DEFAULT: 'var(--color-theme)',
    hover: 'var(--color-theme-hover)',
    contrast: 'var(--color-theme-contrast)',
    reduced: 'var(--color-theme-reduced)',
    active: 'var(--color-theme-active)',
    light: 'var(--color-theme-light)',
  },
  hlt: {
    DEFAULT: 'var(--color-highlight)',
    hover: 'var(--color-highlight-hover)',
    contrast: 'var(--color-highlight-contrast)',
    reduced: 'var(--color-highlight-reduced)',
    active: 'var(--color-highlight-active)',
    light: 'var(--color-highlight-light)',
  },
  cta: {
    DEFAULT: 'var(--color-cta)',
    hover: 'var(--color-cta-hover)',
    contrast: 'var(--color-cta-contrast)',
    reduced: 'var(--color-cta-reduced)',
    active: 'var(--color-cta-active)',
    light: 'var(--color-cta-light)',
  },
  suc: {
    DEFAULT: 'var(--color-success)',
    hover: 'var(--color-success-hover)',
    contrast: 'var(--color-success-contrast)',
    reduced: 'var(--color-success-reduced)',
    active: 'var(--color-success-active)',
    light: 'var(--color-success-light)',
  },
  wrn: {
    DEFAULT: 'var(--color-warning)',
    hover: 'var(--color-warning-hover)',
    contrast: 'var(--color-warning-contrast)',
    reduced: 'var(--color-warning-reduced)',
    active: 'var(--color-warning-active)',
    light: 'var(--color-warning-light)',
  },
  err: {
    DEFAULT: 'var(--color-error)',
    hover: 'var(--color-error-hover)',
    contrast: 'var(--color-error-contrast)',
    reduced: 'var(--color-error-reduced)',
    active: 'var(--color-error-active)',
    light: 'var(--color-error-light)',
  },
}
